[package]
name = "harmony"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
bincode = "1.3.3"
clap = "4.5.23"
ignore = "0.4.23"
serde = { version = "1.0.217", features = ["derive"] }
sha2 = "0.10.8"
